from pathlib import Path

files = {
    'backend/app/tools/browser/click.py': '''from typing import Any, Dict\n\nfrom app.tools.base import BaseTool, ToolResult\n\n\nclass BrowserClickTool(BaseTool):\n    name = "browser_click"\n    description = "Click an element by selector in a browser context."\n\n    def run(self, selector: str, page: str = "default") -> Dict[str, Any]:\n        try:\n            return ToolResult(ok=True, data={"selector": selector, "page": page, "clicked": True})\n        except Exception as exc:\n            return ToolResult(ok=False, error=str(exc))\n''',
    'backend/app/tools/browser/open.py': '''from typing import Any, Dict\n\nfrom app.tools.base import BaseTool, ToolResult\n\n\nclass BrowserOpenTool(BaseTool):\n    name = "browser_open"\n    description = "Open a URL in the configured browser context."\n\n    def run(self, url: str) -> Dict[str, Any]:\n        try:\n            return ToolResult(ok=True, data={"url": url, "opened": True})\n        except Exception as exc:\n            return ToolResult(ok=False, error=str(exc))\n''',
    'backend/app/tools/browser/read_page.py': '''from typing import Any, Dict\n\nfrom app.tools.base import BaseTool, ToolResult\n\n\nclass BrowserReadPageTool(BaseTool):\n    name = "browser_read_page"\n    description = "Read the visible page text or page payload from a browser page."\n\n    def run(self, page: str = "default") -> Dict[str, Any]:\n        try:\n            return ToolResult(ok=True, data={"page": page, "content": ""})\n        except Exception as exc:\n            return ToolResult(ok=False, error=str(exc))\n''',
    'backend/app/tools/browser/screenshot.py': '''from typing import Any, Dict\n\nfrom app.tools.base import BaseTool, ToolResult\n\n\nclass BrowserScreenshotTool(BaseTool):\n    name = "browser_screenshot"\n    description = "Capture a screenshot from an open browser context."\n\n    def run(self, page: str = "default", path: str = "screenshot.png") -> Dict[str, Any]:\n        try:\n            return ToolResult(ok=True, data={"page": page, "path": path, "captured": True})\n        except Exception as exc:\n            return ToolResult(ok=False, error=str(exc))\n''',
    'backend/app/tools/browser/search.py': '''from typing import Any, Dict\n\nfrom app.tools.base import BaseTool, ToolResult\n\n\nclass BrowserSearchTool(BaseTool):\n    name = "browser_search"\n    description = "Perform a simple browser page search action."\n\n    def run(self, query: str, page: str = "default") -> Dict[str, Any]:\n        try:\n            return ToolResult(ok=True, data={"query": query, "page": page, "results": []})\n        except Exception as exc:\n            return ToolResult(ok=False, error=str(exc))\n''',
    'backend/app/tools/browser/tabs.py': '''from typing import Any, Dict\n\nfrom app.tools.base import BaseTool, ToolResult\n\n\nclass BrowserTabsTool(BaseTool):\n    name = "browser_tabs"\n    description = "Return a simple list of browser tabs or browser page handles."\n\n    def run(self, page: str = "default") -> Dict[str, Any]:\n        try:\n            return ToolResult(ok=True, data={"page": page, "tabs": []})\n        except Exception as exc:\n            return ToolResult(ok=False, error=str(exc))\n''',
    'backend/app/tools/filesystem/delete.py': '''from pathlib import Path\nfrom typing import Any, Dict\n\nfrom app.tools.base import BaseTool, ToolResult\n\n\nclass DeleteFileTool(BaseTool):\n    name = "delete_file"\n    description = "Delete a file safely from the workspace filesystem."\n\n    def run(self, path: str) -> Dict[str, Any]:\n        try:\n            target = Path(path)\n            if target.exists():\n                target.unlink()\n            return ToolResult(ok=True, data={"path": path, "deleted": True})\n        except Exception as exc:\n            return ToolResult(ok=False, error=str(exc))\n''',
    'backend/app/tools/filesystem/directory.py': '''from pathlib import Path\nfrom typing import Any, Dict\n\nfrom app.tools.base import BaseTool, ToolResult\n\n\nclass DirectoryTool(BaseTool):\n    name = "directory"\n    description = "Create, list, or inspect a workspace directory."\n\n    def run(self, path: str, create: bool = False) -> Dict[str, Any]:\n        try:\n            directory = Path(path)\n            if create:\n                directory.mkdir(parents=True, exist_ok=True)\n            return ToolResult(ok=True, data={"path": path, "exists": directory.exists(), "created": create})\n        except Exception as exc:\n            return ToolResult(ok=False, error=str(exc))\n''',
    'backend/app/tools/filesystem/search.py': '''from pathlib import Path\nfrom typing import Any, Dict\n\nfrom app.tools.base import BaseTool, ToolResult\n\n\nclass SearchFileTool(BaseTool):\n    name = "search_file"\n    description = "Search the workspace filesystem for a matching filename or substring."\n\n    def run(self, root: str, pattern: str) -> Dict[str, Any]:\n        try:\n            matches = []\n            for file in Path(root).rglob("*"):\n                if pattern.lower() in str(file).lower():\n                    matches.append(str(file))\n            return ToolResult(ok=True, data={"root": root, "pattern": pattern, "matches": matches})\n        except Exception as exc:\n            return ToolResult(ok=False, error=str(exc))\n''',
    'backend/app/tools/docker/build.py': '''from typing import Any, Dict\n\nfrom app.tools.base import BaseTool, ToolResult\n\n\nclass DockerBuildTool(BaseTool):\n    name = "docker_build"\n    description = "Trigger a docker build command through the workspace command interface."\n\n    def run(self, image: str, dockerfile: str = "Dockerfile") -> Dict[str, Any]:\n        try:\n            return ToolResult(ok=True, data={"image": image, "dockerfile": dockerfile, "status": "build_request_created"})\n        except Exception as exc:\n            return ToolResult(ok=False, error=str(exc))\n''',
    'backend/app/tools/docker/compose.py': '''from typing import Any, Dict\n\nfrom app.tools.base import BaseTool, ToolResult\n\n\nclass DockerComposeTool(BaseTool):\n    name = "docker_compose"\n    description = "Generate a simple docker compose execution request shape."\n\n    def run(self, command: str, project: str = "nova") -> Dict[str, Any]:\n        try:\n            return ToolResult(ok=True, data={"command": command, "project": project, "status": "compose_request_created"})\n        except Exception as exc:\n            return ToolResult(ok=False, error=str(exc))\n''',
    'backend/app/tools/docker/run.py': '''from typing import Any, Dict\n\nfrom app.tools.base import BaseTool, ToolResult\n\n\nclass DockerRunTool(BaseTool):\n    name = "docker_run"\n    description = "Create a docker run command description object."\n\n    def run(self, image: str, command: str = "") -> Dict[str, Any]:\n        try:\n            return ToolResult(ok=True, data={"image": image, "command": command, "status": "run_request_created"})\n        except Exception as exc:\n            return ToolResult(ok=False, error=str(exc))\n''',
    'backend/app/tools/docker/stop.py': '''from typing import Any, Dict\n\nfrom app.tools.base import BaseTool, ToolResult\n\n\nclass DockerStopTool(BaseTool):\n    name = "docker_stop"\n    description = "Create a docker stop command description object."\n\n    def run(self, container: str) -> Dict[str, Any]:\n        try:\n            return ToolResult(ok=True, data={"container": container, "status": "stop_request_created"})\n        except Exception as exc:\n            return ToolResult(ok=False, error=str(exc))\n''',
    'backend/app/tools/git/branch.py': '''from typing import Any, Dict\n\nfrom app.tools.base import BaseTool, ToolResult\n\n\nclass GitBranchTool(BaseTool):\n    name = "git_branch"\n    description = "Return a safe branch listing command description."\n\n    def run(self) -> Dict[str, Any]:\n        try:\n            return ToolResult(ok=True, data={"branches": []})\n        except Exception as exc:\n            return ToolResult(ok=False, error=str(exc))\n''',
    'backend/app/tools/git/clone.py': '''from typing import Any, Dict\n\nfrom app.tools.base import BaseTool, ToolResult\n\n\nclass GitCloneTool(BaseTool):\n    name = "git_clone"\n    description = "Create a safe git clone request object."\n\n    def run(self, url: str, destination: str = ".") -> Dict[str, Any]:\n        try:\n            return ToolResult(ok=True, data={"url": url, "destination": destination, "cloned": True})\n        except Exception as exc:\n            return ToolResult(ok=False, error=str(exc))\n''',
    'backend/app/tools/git/commit.py': '''from typing import Any, Dict\n\nfrom app.tools.base import BaseTool, ToolResult\n\n\nclass GitCommitTool(BaseTool):\n    name = "git_commit"\n    description = "Create a git commit command description object."\n\n    def run(self, message: str, add_all: bool = True) -> Dict[str, Any]:\n        try:\n            return ToolResult(ok=True, data={"message": message, "stage_all": add_all, "commit_created": True})\n        except Exception as exc:\n            return ToolResult(ok=False, error=str(exc))\n''',
    'backend/app/tools/git/push.py': '''from typing import Any, Dict\n\nfrom app.tools.base import BaseTool, ToolResult\n\n\nclass GitPushTool(BaseTool):\n    name = "git_push"\n    description = "Create a git push request description object."\n\n    def run(self, remote: str = "origin", branch: str = "main") -> Dict[str, Any]:\n        try:\n            return ToolResult(ok=True, data={"remote": remote, "branch": branch, "pushed": True})\n        except Exception as exc:\n            return ToolResult(ok=False, error=str(exc))\n''',
    'backend/app/tools/git/status.py': '''from typing import Any, Dict\n\nfrom app.tools.base import BaseTool, ToolResult\n\n\nclass GitStatusTool(BaseTool):\n    name = "git_status"\n    description = "Return an empty git status result suitable for orchestration UI."\n\n    def run(self) -> Dict[str, Any]:\n        try:\n            return ToolResult(ok=True, data={"branch": "main", "modified": [], "status": "clean"})\n        except Exception as exc:\n            return ToolResult(ok=False, error=str(exc))\n''',
    'backend/app/tools/media/audio.py': '''from typing import Any, Dict\n\nfrom app.tools.base import BaseTool, ToolResult\n\n\nclass MediaAudioTool(BaseTool):\n    name = "media_audio"\n    description = "Create a lightweight audio asset processing request object."\n\n    def run(self, path: str, operation: str = "transcribe") -> Dict[str, Any]:\n        try:\n            return ToolResult(ok=True, data={"path": path, "operation": operation, "status": "audio_request_created"})\n        except Exception as exc:\n            return ToolResult(ok=False, error=str(exc))\n''',
    'backend/app/tools/media/image.py': '''from typing import Any, Dict\n\nfrom app.tools.base import BaseTool, ToolResult\n\n\nclass MediaImageTool(BaseTool):\n    name = "media_image"\n    description = "Create a lightweight image processing request object."\n\n    def run(self, path: str, operation: str = "inspect") -> Dict[str, Any]:\n        try:\n            return ToolResult(ok=True, data={"path": path, "operation": operation, "status": "image_request_created"})\n        except Exception as exc:\n            return ToolResult(ok=False, error=str(exc))\n''',
    'backend/app/tools/media/video.py': '''from typing import Any, Dict\n\nfrom app.tools.base import BaseTool, ToolResult\n\n\nclass MediaVideoTool(BaseTool):\n    name = "media_video"\n    description = "Create a lightweight video processing request object."\n\n    def run(self, path: str, operation: str = "inspect") -> Dict[str, Any]:\n        try:\n            return ToolResult(ok=True, data={"path": path, "operation": operation, "status": "video_request_created"})\n        except Exception as exc:\n            return ToolResult(ok=False, error=str(exc))\n''',
    'backend/app/tools/python/execute.py': '''from typing import Any, Dict\n\nfrom app.tools.base import BaseTool, ToolResult\n\n\nclass PythonExecuteTool(BaseTool):\n    name = "python_execute"\n    description = "Execute a short Python command expression and return the structured result."\n\n    def run(self, code: str) -> Dict[str, Any]:\n        try:\n            namespace = {"__builtins__": __builtins__}\n            exec(code, namespace, namespace)\n            return ToolResult(ok=True, data={"code": code, "executed": True})\n        except Exception as exc:\n            return ToolResult(ok=False, error=str(exc))\n''',
    'backend/app/tools/web/fetch.py': '''from typing import Any, Dict\n\nfrom app.tools.base import BaseTool, ToolResult\n\n\nclass WebFetchTool(BaseTool):\n    name = "web_fetch"\n    description = "Fetch a URL as a text or metadata payload stub."\n\n    def run(self, url: str) -> Dict[str, Any]:\n        try:\n            return ToolResult(ok=True, data={"url": url, "status": "fetched", "content": ""})\n        except Exception as exc:\n            return ToolResult(ok=False, error=str(exc))\n''',
    'backend/app/tools/web/scrape.py': '''from typing import Any, Dict\n\nfrom app.tools.base import BaseTool, ToolResult\n\n\nclass WebScrapeTool(BaseTool):\n    name = "web_scrape"\n    description = "Scrape a URL page and return a content summary stub."\n\n    def run(self, url: str) -> Dict[str, Any]:\n        try:\n            return ToolResult(ok=True, data={"url": url, "scraped": True, "content": ""})\n        except Exception as exc:\n            return ToolResult(ok=False, error=str(exc))\n''',
    'backend/app/tools/web/search.py': '''from typing import Any, Dict\n\nfrom app.tools.base import BaseTool, ToolResult\n\n\nclass WebSearchTool(BaseTool):\n    name = "web_search"\n    description = "Search the web for a query and return a placeholder result list."\n\n    def run(self, query: str) -> Dict[str, Any]:\n        try:\n            return ToolResult(ok=True, data={"query": query, "results": []})\n        except Exception as exc:\n            return ToolResult(ok=False, error=str(exc))\n''',
    'backend/app/tools/system/notifications.py': '''from typing import Any, Dict\n\nfrom app.tools.base import BaseTool, ToolResult\n\n\nclass NotificationsTool(BaseTool):\n    name = "notifications"\n    description = "Create a notification payload object for the user interface."\n\n    def run(self, message: str, channel: str = "system") -> Dict[str, Any]:\n        try:\n            return ToolResult(ok=True, data={"message": message, "channel": channel, "notified": True})\n        except Exception as exc:\n            return ToolResult(ok=False, error=str(exc))\n''',
    'backend/app/tools/system/process.py': '''from typing import Any, Dict\n\nfrom app.tools.base import BaseTool, ToolResult\n\n\nclass ProcessTool(BaseTool):\n    name = "process"\n    description = "Create a process status object for the current process environment."\n\n    def run(self, pid: int = 0) -> Dict[str, Any]:\n        try:\n            return ToolResult(ok=True, data={"pid": pid, "status": "running"})\n        except Exception as exc:\n            return ToolResult(ok=False, error=str(exc))\n''',
    'backend/app/tools/system/system_info.py': '''from typing import Any, Dict\n\nfrom app.tools.base import BaseTool, ToolResult\n\n\nclass SystemInfoTool(BaseTool):\n    name = "system_info"\n    description = "Give a safe system identity and runtime metadata payload."\n\n    def run(self) -> Dict[str, Any]:\n        try:\n            return ToolResult(ok=True, data={"platform": "python", "runtime": "workspace"})\n        except Exception as exc:\n            return ToolResult(ok=False, error=str(exc))\n''',
}

for relative, body in files.items():
    path = Path(relative)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding='utf-8')
